### ISSUE TITLE
[Feature] Label 공통 컴포넌트 구현

### ISSUE THREAD

**Issue by HoberMin** [BoardSignal/Team-CivilWar-BoardSignal-FE#29]
## 🤷‍♂️ 내용 요약

- [ ] 현재 TextInput 컴포넌트에 있는 Label을 다른곳에서도 사용할 수 있도록 분리하고자 합니다.
- [ ] Label 의 props는 PR에 같이 정리해서 추가해놓도록 하겠습니다.

## 📒 특이사항
<img width="366" alt="image" src="https://github.com/BoardSignal/Team-CivilWar-BoardSignal-FE/assets/102784200/f58ba8e9-a128-4d58-aa1a-4c0fc1e8ed6c">

**Comment by seongbin9786** [comment]
Text와 TextArea의 경우에는 글자수 제한도 있어서
혹시 해당 부분 구현하시는지도 작성해주시면 더 명확한 작업 범위가 될 수도 있을 것 같아요 :)

**Comment by HoberMin** [comment]
글자수 제한 부분도 같이 구현해보도록 하겠습니다 ! Form 태그에서 상태를 props로 내려줘야할것 같아서 onChange까지 구현하도록 할게요 !
