### ISSUE TITLE
[Feat] 프로필 조회 페이지

### ISSUE THREAD

**Issue by HoberMin** [BoardSignal/Team-CivilWar-BoardSignal-FE#30]
## 🤷‍♂️ 내용 요약

- [ ] 닉네임
- [ ] 참여한 게임 수 - Signal
- [ ] 내가 선택한 카테고리
- [ ] 성별
- [ ] 연령대
- [ ] 이미지
- [ ] 시그널 온도
- [ ] 남겨진 리뷰

### 프로필 수정으로 가는 버튼도 없네요 같이 잡아야 할 것 같아요.

<img width="384" alt="image" src="https://github.com/BoardSignal/Team-CivilWar-BoardSignal-FE/assets/102784200/e6663e41-29e1-4c92-8c3c-5572f6f5c162">

**Comment by seongbin9786** [comment]
제가 적어도 내일 오후까지 Figma 업보 청산을 하도록 하겠습니다. 죄송합니다 :(

**Comment by HoberMin** [comment]
업보랄건 아니었구요.. 같이 해야할 일이라고 생각해서 남겨둔 내용입니다 !!

**Comment by seongbin9786** [comment]
<프로필 수정 버튼>과 <로그아웃 버튼> 추가 되었고 <설정 버튼>과 <로그아웃 버튼> 시의 모달 추가했어요.

<img src="https://github.com/BoardSignal/Team-CivilWar-BoardSignal-FE/assets/28754907/ef66cf1f-750c-4f29-b575-72ae3f60b112" width="500" />

<img src="https://github.com/BoardSignal/Team-CivilWar-BoardSignal-FE/assets/28754907/d0898a01-1f7e-4deb-9d99-0abaf23ec06c" width="500" />
