### ISSUE TITLE
[Feat] 공통컴포넌트 - MultipleSelect

### ISSUE THREAD

**Issue by Heeeera** [BoardSignal/Team-CivilWar-BoardSignal-FE#31]
## 🤷‍♂️ 내용 요약
 버튼을 다중 선택할 수 있는 컴포넌트

- [ ] `items`, `onClick`, `selectedItems`(기존에 선택된 버튼 리스트)를 props로 받도록 구현

<img src="https://github.com/BoardSignal/Team-CivilWar-BoardSignal-FE/assets/42732729/62842185-1aa2-40ef-9d26-f6ff4a48c410" width="50%">

## 📒 특이사항
- 컴포넌트 이름을 `MultiSelect`로 하면 다중 선택이 가능한 `<select>` 느낌이 날 것 같아서 `MultiButtonSelect`로 했는데, 더 좋은 아이디어가 있다면 공유해주세요!

**Comment by seongbin9786** [comment]
`MultiButtonSelect`는 좋은 시도인 것 같아요.

저는 `<SelectableChips>`가 조금 더 간결할 수 있을 것 같은데요,

표시되는 요소는 `Chip`이기 때문에 `Chip`이라는 이름은 들어가야 할 것 같아요.

`Multi`의 경우 `Multiple`로 써야 약어가 아니게 될 것 같아서 `Multiple`로 한다면...
`Multiple`이 단어가 조금 긴 감이 있어서 `s`를 붙여 떼우면.. `Chips`...

그냥 `Chips`라고 붙이면 Select의 의미가 없어서, `Selectable`을 붙여봤어요 :)

그래서 `SelectableChips`라는 결론을 내었어요
