### ISSUE TITLE
[Feat] 공통 컴포넌트 - ImageUpload

### ISSUE THREAD

**Issue by lja0395** [BoardSignal/Team-CivilWar-BoardSignal-FE#43]
## 🤷‍♂️ 내용 요약

- [x] 회원가입, 프로필수정, 모임생성시에 사용하는 이미지업로드 컴포넌트를 구현합니다.

![image](https://github.com/BoardSignal/Team-CivilWar-BoardSignal-FE/assets/99376069/98f18e4f-e89f-4376-80ad-417e1f37f2bd)

**Comment by seongbin9786** [comment]
네모난 variant도 같이 스펙에 포함시켜주시면 좋을 것 같아요~! :)
