### ISSUE TITLE
[Feat] 프로필조회페이지 - 매너온도 구현

### ISSUE THREAD

**Issue by HoberMin** [BoardSignal/Team-CivilWar-BoardSignal-FE#45]
## 🤷‍♂️ 내용 요약

- [x] 매너온도에 대한 툴팁을 구현하려고 합니다
- [x] 온도값에 따른 Progress 를 구현하려고 합니다

## 📒 특이사항

<img width="620" alt="image" src="https://github.com/BoardSignal/Team-CivilWar-BoardSignal-FE/assets/102784200/e41c66a4-32ec-4add-8327-8b0258deb079">

매너온도 => 시그널온도로 변경했던 것 같은데 해당 내용 댓글로 부탁드리겠습니다.

**Comment by seongbin9786** [comment]
시그널온도가 맞습니다 :)
