### ISSUE TITLE
[Feat] 모임 확정 입력 페이지

### ISSUE THREAD

**Issue by HoberMin** [BoardSignal/Team-CivilWar-BoardSignal-FE#82]
## 🤷‍♂️ 내용 요약

- [ ] Tabbar
- [ ] Alert
- [ ] Form 디자인
- [ ] 모임 확정하기 버튼
- [ ] 확정 모달

## 📒 특이사항
* 시작시간 설정을 어떻게 할건지 디자인이 없어서 논의해봐야 할 것 같습니다.
* 지역, 장소는 텍스트로 입력하게 처리한 이후 재작업하겠습니다.

<img width="318" alt="image" src="https://github.com/BoardSignal/Team-CivilWar-BoardSignal-FE/assets/102784200/02c0c7c1-022f-4a93-9e10-aea7730febba">

**Comment by seongbin9786** [comment]
타임 피커도 논의되다 말아서 일단 TextInput으로 부탁드립니다 ㅠㅠ
